- tuiexporter/internal/tui/component/timeline.go
- tuiexporter/internal/tui/component/timeline_test.go
- prettier prefix of spans
- dynamic time unit supporting
more than millisecs
less than millisecs
> improve timeline UI

- tuiexporter/internal/telemetry/cache.go
- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/telemetry/store_test.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/tui.go
> feat: data flush support

- tuiexporter/internal/tui/component/timeline.go
> feat: Colorize trace timeline

- .github/workflows/release.yml
- .goreleaser.yaml
- README.md
> Add workflow to release to homebrew tap

- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/timeline.go
> Improve readability of key maps

- tuiexporter/internal/tui/component/log.go
- tuiexporter/internal/tui/component/log_test.go
closes: #132
Add a column of `event.name` in the list of Logs. It'll be `N/A<Event Name>` if `event.name` is not set.
Screenshot
> Add event name ( `event.name` ) column in the list of Logs

- go.work.sum
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/timeline.go
closes: #131
Resize details pane by pressing `Ctrl+H` and `Ctrl+L` in:
- traces
- including the timeline page
- metrics
- logs
> Make all the details panes resizable by Ctrl+H and Ctrl+L

- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/telemetry/store_test.go
- tuiexporter/internal/tui/component/page.go
closes: #118 
This change enables us to filter traces by span name in addition to service name.
> Filter traces by service and span name

- tuiexporter/internal/tui/component/commands.go
- tuiexporter/internal/tui/component/log.go
- tuiexporter/internal/tui/component/log_test.go
- tuiexporter/internal/tui/component/metric.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/timeline.go
- tuiexporter/internal/tui/component/trace.go
- tuiexporter/internal/tui/component/trace_test.go
closes: #92
focused on the traces pane
focused on the search form
focused on the timeline pane
> Display keymaps corresponding to focused pane, not page

- tuiexporter/internal/telemetry/cache.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/timeline.go
- tuiexporter/internal/tui/component/trace.go
- tuiexporter/internal/tui/component/trace_test.go
closes: #137 
Mark the error spans with `[!]` (in table) and `⚠️` (in details) . 
traces:
timeline:
> Mark the error spans in traces and timeline page

- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/tui/component/metric.go
> Support Histogram in summary chart pane

- tuiexporter/internal/tui/component/trace.go
- tuiexporter/internal/tui/component/trace_test.go
> Replace trace ID with latency in trace list

- go.mod
- go.sum
- go.work.sum
- tuiexporter/internal/telemetry/sort.go
- tuiexporter/internal/telemetry/sort_test.go
- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/telemetry/store_test.go
- tuiexporter/internal/test/tracegen.go
- tuiexporter/internal/tui/component/log.go
- tuiexporter/internal/tui/component/metric.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/trace.go
- tuiexporter/internal/tui/component/trace_test.go
closes: #18 
This change adds the feature to sort by the span latency (`NONE`, `DESC`, `ASC`) with `Ctrl+S`. If `NONE` is selected, the spans are implicitly sorted by `received_at` in ascending order.
None
Desc
Asc
> Add feature of sorting by the span latency

- tuiexporter/internal/tui/component/log.go
- tuiexporter/internal/tui/component/log_test.go
- tuiexporter/internal/tui/component/metric.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/component/timeline.go
- tuiexporter/internal/tui/component/trace.go
- tuiexporter/internal/tui/component/trace_test.go
- tuiexporter/internal/tui/component/tree.go
related: #164 
This PR provides the following feature:
- The modal which shows full text of the selected node
- Toggle by pressing `Enter` (also, it disappears when the selection changed)
- Scroll with the key `Ctrl+J`, `Ctrl+K`
> Full text modal for attribute tree

- tuiexporter/internal/tui/component/page.go
related: #186 
Clear the related panes like details when clearing data on `Ctrl+L`
|signal|||
|---|---|---|
| Trace | ![image](https://github.com/user-attachments/assets/c9e26d96-770c-4588-8d23-e5047b1b6ca0) | ![image](https://github.com/user-attachments/assets/8dd754e9-49b1-4964-95e9-5a6854650ffd) |
| Metric | ![image](https://github.com/user-attachments/assets/db8a9eb1-2140-4626-86e1-45123fdeef49) | ![image](https://github.com/user-attachments/assets/0e7dfac1-9814-4269-bd36-cecbaad1153c) |
| Log | ![image](https://github.com/user-attachments/assets/a1e7116e-285f-40a2-a7be-50b500fa3504) | ![image](https://github.com/user-attachments/assets/43ea40fc-6ddb-4fa8-937d-348786668256) |
> Clear the related panes on `Ctrl+L`

- go.work.sum
- main.go
small change to enable the Prometheus receiver feature if Prometheus
targets are provided. as a new user I was confused why my Prometheus
targets wouldn't populate metrics until I saw there was a separate
enablement flag
> fix: enable prom reciever if prom targets given

- tuiexporter/internal/tui/component/modal.go
- tuiexporter/internal/tui/component/modal_test.go
This PR solves the issue of printing JSON formatted attribute value.
related: #223
> fix: pretty print JSON attribute

- README.md
- config.yml.tpl
- config_test.go
related: #236 
Allow otel-tui to receive telemetries sent from `localhost`.
https://opentelemetry.io/docs/languages/js/getting-started/browser/
`document-load.ts`
```ts
import {
ConsoleSpanExporter,
SimpleSpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { WebTracerProvider } from '@opentelemetry/sdk-trace-web';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-proto';
import { DocumentLoadInstrumentation } from '@opentelemetry/instrumentation-document-load';
import { ZoneContextManager } from '@opentelemetry/context-zone';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
const exporter = new OTLPTraceExporter({
// optional - default url is http://localhost:4318/v1/traces
url: 'http://localhost:4318/v1/traces',
// optional - …
```
> feat: allow telemetries sent from localhost

- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/tui/component/log.go
- tuiexporter/internal/tui/component/log_test.go
Uses `ms` precision in the list of logs, also uses an ISO3601-ish format (probably should use a consistent format everywhere?)
> fix: use ISO-ish format, add ms and TZ to log timestamps

- go.work.sum
- tuiexporter/internal/telemetry/store.go
- tuiexporter/internal/tui/component/page.go
closes: #214 
This change resolve the issue that the detail is not updated until the second telemetry is received.
To achieve this, I added callbacks to `Store` to trigger `table.selectionChangedFunc` with current selection when the store is updated.
> feat(ui): re-select when the store is updated and add nil check

- go.work.sum
- tuiexporter/internal/telemetry/store_test.go
- tuiexporter/internal/test/metricgen.go
- tuiexporter/internal/tui/component/metric.go
- tuiexporter/internal/tui/component/metric_test.go
related: #274
This PR fixes a panic that occurred when processing histogram datapoints with only one bucket (i.e., no explicit bounds).  
It adds a conditional branch to safely handle the case where `ExplicitBounds.Len() == 0`.
> fix(metrics): panic when bucket count length is 1

- README.md
- config.go
- config.yml.tpl
- config_test.go
- go.work.sum
- main.go
related: #282 
This PR changes `--prom-endpoint` to accept full HTTP URL.
Valid URLs:
- `http://example.com:1234/custom/metrics`
- `http://example.com:1234`
- `example.com:1234`
- ...
- Clone https://github.com/brancz/prometheus-example-app
- Change the Prometheus endpoint and run
```go
// mux.Handle("/metrics", promhttp.HandlerFor(r, promhttp.HandlerOpts{}))
mux.Handle("/custom/prometheus", promhttp.HandlerFor(r, promhttp.HandlerOpts{}))
```
- run otel-tui
```
go run ./... --enable-prom --prom-target http://localhost:8080/custom/prometheus
go run ./... --enable-prom --prom-target localhost:8080/custom/prometheus
go run ./... --enable-prom --prom-target localhost:8080
```
> feat(metric): Support full HTTP URL for Prometheus

- README.md
- config.go
- config.yml.tpl
- config_test.go
- main.go
- tuiexporter/config.go
- tuiexporter/exporter.go
- tuiexporter/exporter_test.go
- tuiexporter/factory.go
- tuiexporter/internal/tui/component/page.go
- tuiexporter/internal/tui/tui.go
This PR suppresses all stdout/stderr output from OpenTelemetry Collector components by default, and adds a `--debug-log` option to redirect logs to a file (`/tmp/otel-tui.log`).
It also fixes an issue where the application required pressing Ctrl+C twice to exit.
This change addresses cases like #289, where unexpected output to stdout can corrupt the TUI screen.
> feat: suppress stdout/err and add `--debug-log` option

- config.go
- config.yml.tpl
- config_test.go
With this change, I can now scrape archgw like this:
```bash
otel-tui --prom-target http://localhost:19901/stats?format=prometheus
```
> feat(metric): Parse params in HTTP URL for Prometheus

- .goreleaser.yaml
release action is failing due to the following erorr:
```
error=failed to build for windows_386: exit status 1: # go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/internal/envconfig
```
https://github.com/ymtdzzz/otel-tui/actions/runs/18298968842/job/52103991650
This is not a fundamental fix, but since I believe there are few users of i386, I'll exclude it from the build targets.
> chore(goreleaser): remove i386 from build target
